=== rohinigunalan/MyRepo/Newfolder/DSR_AWS/DSR_Schma_Validation/dsr-confirmation.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "requestId": {"type": "string"},
    "appId": {"type": "number"},
    "action": {"type": "string"},
    "detail": {
      "type": "object",
      "properties": {
        "responseDetails": {
          "type": "object",
          "properties": {
            "delete": {
              "type": "object",
              "properties": {
                "subjects": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "firstName": {"type": "string"},
                      "lastName": {"type": "string"},
                      "middleName": {"type": "string"},
                      "personId": {"type": "string"},
                      "gender": {"type": "string"},
                      "birthdate": {"type": "string"},
                      "studentIds": {
                        "type": "array",
                        "items": {"type": "string"}
                      },
                      "domains": {
                        "type": "object",
                        "properties": {
                          "sat": {
                            "type": "object",
                            "properties": {
                              "registration": {
                                "type": "array",
                                "items": {
                                  "type": "object",
                                  "properties": {
                                    "registrationNumber": {"type": "string"}
                                  },
                                  "additionalProperties": false
                                }
                              }
                            },
                            "additionalProperties": false
                          },
                          "psat": {
                            "type": "object",
                            "properties": {
                              "registration": {
                                "type": "array",
                                "items": {
                                  "type": "object",
                                  "properties": {
                                    "registrationNumber": {"type": "string"}
                                  },
                                  "additionalProperties": false
                                }
                              }
                            },
                            "additionalProperties": false
                          },
                          "accommodationsManagement": {
                            "type": "object",
                            "properties": {
                              "data": {
                                "type": "object",
                                "properties": {
                                  "ssdStudentExtraInfo": {
                                    "type": "array",
                                    "items": {
                                      "type": "object",
                                      "properties": {
                                        "ssdStudentId": {"type": "string"}
                                      },
                                      "additionalProperties": false
                                    }
                                  },
                                  "accommodations": {
                                    "type": "array",
                                    "items": {
                                      "type": "object",
                                      "properties": {
                                        "categoryName": {"type": "string"},
                                        "accommodationName": {"type": "string"},
                                        "accommodationStatus": {"type": "string"},
                                        "creationDate": {"type": "string"},
                                        "decisionDate": {"type": "string"},
                                        "expiration": {"type": "string"},
                                        "schoolBased": {"type": "boolean"},
                                        "statusDate": {"type": "string"},
                                        "supplementalInfo": {"type": "string"}
                                      },
                                      "additionalProperties": false
                                    }
                                  }
                                },
                                "additionalProperties": false
                              }
                            },
                            "additionalProperties": false
                          }
                        },
                        "additionalProperties": false
                      }
                    },
                    "additionalProperties": false
                  }
                }
              },
              "additionalProperties": false
            },
            "information": {
              "type": "object",
              "properties": {
                "subjects": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "firstName": {"type": "string"},
                      "lastName": {"type": "string"},
                      "middleName": {"type": "string"},
                      "personId": {"type": "string"},
                      "gender": {"type": "string"},
                      "birthdate": {"type": "string"},
                      "studentIds": {
                        "type": "array",
                        "items": {"type": "string"}
                      },
                      "domains": {
                        "type": "object",
                        "properties": {
                          "sat": {
                            "type": "object",
                            "properties": {
                              "registration": {
                                "type": "array",
                                "items": {
                                  "type": "object",
                                  "properties": {
                                    "registrationNumber": {"type": "string"}
                                  },
                                  "additionalProperties": false
                                }
                              }
                            },
                            "additionalProperties": false
                          },
                          "psat": {
                            "type": "object",
                            "properties": {
                              "registration": {
                                "type": "array",
                                "items": {
                                  "type": "object",
                                  "properties": {
                                    "registrationNumber": {"type": "string"}
                                  },
                                  "additionalProperties": false
                                }
                              }
                            },
                            "additionalProperties": false
                          },
                          "accommodationsManagement": {
                            "type": "object",
                            "properties": {
                              "data": {
                                "type": "object",
                                "properties": {
                                  "ssdStudentExtraInfo": {
                                    "type": "array",
                                    "items": {
                                      "type": "object",
                                      "properties": {
                                        "ssdStudentId": {"type": "string"}
                                      },
                                      "additionalProperties": false
                                    }
                                  },
                                  "accommodations": {
                                    "type": "array",
                                    "items": {
                                      "type": "object",
                                      "properties": {
                                        "categoryName": {"type": "string"},
                                        "accommodationName": {"type": "string"},
                                        "accommodationStatus": {"type": "string"},
                                        "creationDate": {"type": "string"},
                                        "decisionDate": {"type": "string"},
                                        "expiration": {"type": "string"},
                                        "schoolBased": {"type": "boolean"},
                                        "statusDate": {"type": "string"},
                                        "supplementalInfo": {"type": "string"}
                                      },
                                      "additionalProperties": false
                                    }
                                  }
                                },
                                "additionalProperties": false
                              }
                            },
                            "additionalProperties": false
                          }
                        },
                        "additionalProperties": false
                      }
                    },
                    "additionalProperties": false
                  }
                }
              },
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
}

=== rohinigunalan/MyRepo/Newfolder/DSR_AWS/DSR_Schma_Validation/new505.json
{

    "requestId": "MFCREP8A95_1",

    "appId": 505,

    "action": "EXECUTED",

    "detail": {

        "responseDetails": {

            "information": {

                "subjects": [
         {
            "firstName":"Robert",
            "lastName":"Smith",
            "middleName":"S",
            "personId":"200809165",
            "gender":"Female",
            "birthdate":"09/01/1981",
            "studentIds":[
               "8140131335",
               "8140131337",
               "8150231335"
            ],
            "domains":{
               "sat":{
                  "registration":[
                     {
                        "registrationNumber":"S4561264"
                     }
                  ]
               },
               "psat":{
                  "registration":[
                     {
                        "registrationNumber":"P4561264"
                     }
                  ]
               },
               "accommodationsManagement":{
                  "data":{
                     "ssdStudentExtraInfo":[
                        {
                           "ssdStudentId":"231096000"
                        }
                     ],
                     "accommodations":[
                        {
                           "categoryName":"Extended Time",
                           "accommodationName":"Reading: Up to Time and One-Half (+50%)",
                           "accommodationStatus":"Approved",
                           "creationDate":"12/05/2024",
                           "decisionDate":"12/18/2024",
                           "expiration":"06/30/2027",
                           "schoolBased":true,
                           "statusDate":"12/18/2024",
                           "supplementalInfo":""
                        }
                     ]
                  }
               }
            }
         }
      ]
   }
}
 }
}
